### ISSUE TITLE
Download 

### ISSUE THREAD

**Issue by Sahil01125** [z-huang/InnerTune#651] opened 2023-05-02 16:29 UTC
java.lang.UnsupportedOperationException
	at k8.g.u(Unknown Source:5)
	at k8.g.e(SourceFile:10)
	at z8.t.u(SourceFile:58)
	at va.a.m(Unknown Source:8)
	at lb.n0.run(Unknown Source:100)
	at rb.a$a.run(SourceFile:82)

**Comment by selurvedu** [comment] 2023-05-03 16:58
You should have filed the bug report properly by filling the [corresponding form](https://github.com/z-huang/InnerTune/issues/new?assignees=&labels=bug&template=bug_report.yml). With no context given, it's impossible to understand what you were trying to achieve and how you encountered this error.

"Download" doesn't even tell what kind of problem you're having, it only vaguely hints that it's something related to downloads.

However, this stack trace is exactly the same as in #551, so I think it's a duplicate of that issue.

**Closed** 2023-06-10 11:10 UTC
