### ISSUE TITLE
Some songs ask me to sign in and verify my age

### ISSUE THREAD

**Issue by HiddenLeveI** [z-huang/InnerTune#644] opened 2023-04-12 02:58 UTC
Title says it all, I see no way to bypass the restriction. This is a problem for songs and videos.

**Comment by DeadSecTr** [comment] 2023-04-14 23:53
Can you show us a screenshot from that?

**Comment by HiddenLeveI** [comment] 2023-04-17 15:21
My github client doesn't let me comment images, so here is an email of an image.-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Apr 14, 2023, 7:53 PM by ***@***.***:

**Comment by ctntt** [comment] 2023-05-01 17:25
I tried to reproduce this and I found a song which needs age verification: https://music.youtube.com/watch?v=bSxamZkk8z0

![Screenshot_20230501-192202_Trebuchet](https://user-images.githubusercontent.com/115667885/235496463-4357a90d-2a39-466d-9f57-5c0166bb77ac.png)

**Comment by HiddenLeveI** [comment] 2023-05-16 01:45
![Screenshot_20230515-214425.png](https://github.com/z-huang/InnerTune/assets/110350004/2bbb903c-613f-401b-bc79-3fd1b3975ce6)

**Comment by z-huang** [comment] 2023-06-16 14:55
Duplicate of #443

**Closed by z-huang** 2023-06-16 14:55 UTC
