### ISSUE TITLE
Option between grid and list

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#750] opened 2023-07-05 07:40 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Using on the following tabs.
Playlists and artist tabs.

### Why do you want this feature?

Looks amazing and would be better for the artist page to.

### Additional information

Example from spotify.

https://github.com/z-huang/InnerTune/assets/96526481/ef249cdb-4ab2-40c1-a6b3-50862f641418

**Comment by z-huang** [comment] 2023-07-05 07:42
Duplicate of #279

**Closed by z-huang** 2023-07-05 07:42 UTC
Labels: enhancement

**Comment by owencz1998** [comment] 2023-07-05 07:43
> Duplicate of #279

My bad lol
