### ISSUE TITLE
Opening Artist pane offline produces error

### ISSUE THREAD

**Issue by suhan-paradkar** [z-huang/InnerTune#581] opened 2023-02-16 11:22 UTC
This usually happens if you yeet `Error` instead of `IOException` HTTP requests...

Here's the stacktrace

```java.net.UnknownHostException: Unable to resolve host "music.youtube.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:126)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
	at java.net.InetAddress.getAllByName(InetAddress.java:1154)
	at dc.m.a(Unknown Source:5)
	at hc.d.a(SourceFile:385)
	at hc.a.a(SourceFile:64)
	at ic.f.b(SourceFile:144)
	at fc.a.a(SourceFile:150)
	at ic.f.b(SourceFile:144)
	at ic.a.a(SourceFile:153)
	at ic.f.b(SourceFile:144)
	at ic.h.a(SourceFile:155)
	at ic.f.b(SourceFile:144)
	at hc.e.g(SourceFile:97)
	at hc.e$a.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by z-huang** [comment] 2023-02-16 11:26
Duplicate of #246

**Closed** 2023-02-16 11:26 UTC
Labels: duplicate
