### ISSUE TITLE
Blurred Album art 

### ISSUE THREAD

**Issue by mjain234** [z-huang/InnerTune#441] opened 2022-11-24 18:39 UTC
There is always a ![blurry](https://user-images.githubusercontent.com/70900505/203848418-fbec94a7-751a-4a6f-bd1c-9004924cdf5f.png) album art while playing any song. Is this a known issue? 

Device - Realme 2 Pro

Android - v13

ROM - Arrow OS

Innertune - v0.4.3

**Comment by z-huang** [comment] 2022-11-25 00:25
Duplicate of #244

**Closed** 2022-11-25 00:25 UTC
