### ISSUE TITLE
Stops playing suddenly 

### ISSUE THREAD

**Issue by Vishcot** [z-huang/InnerTune#1000] opened 2023-08-25 18:11 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play songs, 
And sometimes it stops with an error 

### Expected behavior

Should play seamlessly 

### Actual behavior

Stops and never plays songs untill you go and force stop app and come back again.

### Screenshots/Screen recordings

![Screenshot_20230825-233648](https://github.com/z-huang/InnerTune/assets/136909951/186cdf14-f6ed-4f7a-918e-f4fbedf8ca3c)

### InnerTune version

0.5.2

### Android version

Android 14

**Comment by z-huang** [comment] 2023-08-27 02:17
Duplicate of #856

**Closed by z-huang** 2023-08-27 02:17 UTC
Labels: bug
