### ISSUE TITLE
Change of navigation bar

### ISSUE THREAD

**Issue by eightyy8** [z-huang/InnerTune#526] opened 2023-01-19 18:12 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

All other music apps implement the options to view them in one button, a library button, which nests those same artist, album, playlist and song options to filter your saved music within it - far more convenient.

Spotify's navigation bar:
![pstore-spotimg](https://user-images.githubusercontent.com/64216434/213523552-d6644a20-1774-4e14-8b54-4b82135b2dbf.png)
YouTube Music's navigation bar:
![pstore-ytimg](https://user-images.githubusercontent.com/64216434/213523658-40857474-52ff-4546-9be9-fce87b0ec336.png)

### Why do you want this feature?

The navigation buttons in the bottom bar (or whatever you call them) are overwhelmed unnecessarily, the home button is perfectly fine, it's just the artist, album, playlist and song button that is overwhelming. I know you can disable them but I want to access them.

### Additional information

The search button can be the middle button, definitely one of the most important/useful options.

Really appreciate your work.

**Comment by z-huang** [comment] 2023-01-20 10:02
Duplicate of #173

**Closed by z-huang** 2023-01-20 10:02 UTC
Labels: enhancement

**Comment by eightyy8** [comment] 2023-01-20 21:22
@z-huang Even if you personally prefer it could you add a settings option to change it at least? Most people prefer minimal GUIs.

**Comment by z-huang** [comment] 2023-01-21 03:22
I would call this a "design", not an option. Oto Music and Retro Music use this design, too. Five tabs is still in compliance with Material design. If you really want another appearance, create a fork and make your own.
