### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by DirectiveTaurus** [z-huang/InnerTune#917] opened 2023-08-02 13:07 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Pls add discord rpc I've came to see a lot of open source apps are now adding discord rich prcense. 

### Why do you want this feature?

It would be cool to let other see using your app and showing what song you're listening to.

**Comment by z-huang** [comment] 2023-08-03 03:46
Duplicate of #602

**Closed by z-huang** 2023-08-03 03:46 UTC
Labels: enhancement
