### ISSUE TITLE
Foreground icon missing in the launcher.

### ISSUE THREAD

**Issue by tarunbuddy** [z-huang/InnerTune#345] opened 2022-10-22 13:14 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/InnerTune/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

App doesn't have any icon in the launcher. It only shows white background.

### Expected behavior

Icon should be there.

### Actual behavior

There is no foreground icon. 

### Screenshots/Screen recordings

![Screenshot_2022-10-22-18-40-45-26_b783bf344239542886fee7b48fa4b892~2](https://user-images.githubusercontent.com/39480406/197340908-a90a4f6f-4c58-42f8-9c6e-3d3e518a12fe.jpg)

### Music version

"0.4.2"

### Android version

Android 12

**Comment by z-huang** [comment] 2022-10-22 13:58
Duplicate of #230

**Closed by z-huang** 2022-10-22 13:58 UTC
Labels: bug
