### ISSUE TITLE
Album art as wallpaper on lockscreen when playing

### ISSUE THREAD

**Issue by nikhilCad** [z-huang/InnerTune#427] opened 2022-11-13 07:03 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

1. Play song
2. Lock the screen
3. On the lock screen you see you still has your choosen wallpaper, in other music apps and even newpipe the wallpaper of lockscreen changes based on the song art

### Why do you want this feature?

Looks nice

### Additional information

-

**Comment by nikhilCad** [comment] 2022-11-13 07:06
![Screenshot_20221113-123439](https://user-images.githubusercontent.com/47214394/201510117-55618cba-3aab-40e2-9991-0d4e162b14a9.png)

**Comment by z-huang** [comment] 2022-12-05 09:50
Duplicate of #422

**Closed** 2022-12-05 09:50 UTC
Labels: duplicate, enhancement
