### ISSUE TITLE
Add local music support

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [z-huang/InnerTune#867] opened 2023-07-22 11:15 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

This app would be perfect when added support for local music files on the device.

### Why do you want this feature?

There is no great and simple music player for android, this one is really clean but lacks of local music support on the device sadly. Would love to see that

**Comment by z-huang** [comment] 2023-07-22 11:28
Duplicate of #3

**Closed by z-huang** 2023-07-22 11:28 UTC
Labels: enhancement
