### ISSUE TITLE
Controls missing from quick menu and lock screen

### ISSUE THREAD

**Issue by TheSoulWizard** [z-huang/InnerTune#850] opened 2023-07-19 23:26 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

-Lock the screen or swipe down the quick menu panel

-The previous and next buttons will be missing from either.

### Expected behavior

Buttons should appear like this
![Screenshot_2023-07-20-02-20-02-04_0438eb925998df20b3482ec25499d226](https://github.com/z-huang/InnerTune/assets/40411642/b279e379-675c-49dd-b30f-bf50bad0275c)

### Actual behavior

Buttons are missing
![Screenshot_2023-07-20-02-10-49-11_f4703f2d42345ac28c56f11a6100c500](https://github.com/z-huang/InnerTune/assets/40411642/d5bce13a-02de-47e7-ba9a-8f83085e10f3)
![Screenshot_2023-07-20-02-10-56-69_f4703f2d42345ac28c56f11a6100c500](https://github.com/z-huang/InnerTune/assets/40411642/5ae90fcc-c5fa-40d3-a65a-84c5dd9557c0)

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/40411642/94b404db-5946-4665-a698-2cce379061a2

### InnerTune version

0.5.0

### Android version

Android 12

### Additional information

Device: OnePlus 7 Pro
Codename: guacamole
OS Skin + Ver.: OxygenOS 12.1 (stock)

**Comment by z-huang** [comment] 2023-07-20 04:10
Duplicate of #808

**Closed by z-huang** 2023-07-20 04:10 UTC
Labels: bug
