### ISSUE TITLE
Playback error on some songs after 30 seconds

### ISSUE THREAD

**Issue by nichtstuer** [z-huang/InnerTune#856] opened 2023-07-20 13:49 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play https://music.youtube.com/watch?v=XLiOcw-HZzo
2.  Wait 30 seconds

### Expected behavior

The playback continues

### Actual behavior

1. Playback stops with error: open failed: ENOENT (no such file or directory).
2. It's not possible to resume playback or play another song in the current queue until the app restart or selecting another album.

### Screenshots/Screen recordings

![innertube-enoent](https://github.com/z-huang/InnerTune/assets/5593541/255aa2b9-90af-4380-90eb-7e89a48369b2)

### Logs

[logcat.txt](https://github.com/z-huang/InnerTune/files/12112961/logcat.txt)

### InnerTune version

0.5.0

### Android version

Android 11

### Additional information

This is my first report, I don't know how to get the debug version

**Comment by TheTrashCrafter** [comment] 2023-07-20 18:00
I don't know anything about what the problem is, but you can get the latest debug version on the actions tab (or you can compile it yourself of course).

**Comment by nichtstuer** [comment] 2023-07-20 18:14
I've tried to play the album in another app and it defaults to the video version you've mentioned (don't know if this info helps).

**Comment by owencz1998** [comment] 2023-08-03 17:05
When using the old version remove the downloads and then backup again then restore but make sure your using the old version of innertune 1st and follow the process then update then restore this worked for me.

**Comment by Kurasami** [comment] 2023-08-15 23:52
Try version 0.5.1 and if it's fixed, close the issue please.

**Comment by AlexIs387** [comment] 2023-08-22 08:48
> > Try version 0.5.1 and if it's fixed, close the issue please.
> 
> Tried with 0.5.1, still happening, not fixed : "jbZusVDBf4A: open failed: ENOENT (No such file or directory) "

And still with the version 0.5.2 which is the latest, I think the real fix is uninstall it.

**Comment by z-huang** [comment] 2023-08-27 02:16
Sorry for the late fix. I can reproduce the bug with this song: [music.youtube.com/watch?v=XLiOcw-HZzo](https://music.youtube.com/watch?v=XLiOcw-HZzo). After the fix, it won't happen for the song. Other songs should be fixed, too. If not, tell me.

**Closed by z-huang** 2023-08-27 02:16 UTC
Labels: bug
