### ISSUE TITLE
Can't get album cover on android wearable device.

### ISSUE THREAD

**Issue by EvadeMaster** [z-huang/InnerTune#597] opened 2023-02-27 15:00 UTC
### 📝 Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### 📝 Steps to reproduce the bug

✅ Prerequisite:
- Own an Android-based wearable device (Wear OS) or an emulator. <br>
1. 📱 Play any song on InnerTune.
2. ⌚ Swipe the Quick Settings Panel down.
3. ⌚ Press the media control button.
4. ⌚ Observe the media control unable to get the album cover, see the picture.

### 😃 Expected behaviour

⌚ Wear OS's music control should render the album cover.

### 🌋 Actual behaviour

⌚ Wear OS's music control uses the default placeholder album cover.

### 📸 Screenshots/Screen recordings

![Never Gonna Let You Down](https://user-images.githubusercontent.com/93124920/221597421-e92be587-86f5-4cb7-9281-ac7478c8fde4.jpg)

### 🎵 Music version

bdf01fb885eb740d7aa566ac8c60b332289ae5ff

### 📱 Android version

Android 13

### Additional information
> **Note** <br>
> ⌚ Wear OS version: Wear OS 2

**Comment by owencz1998** [comment] 2023-02-27 20:03
I think this is similar but I'm using KWGT widgets to make my own for this app but the album cover isn't being detected whiles other apps are working for it.

**Comment by z-huang** [comment] 2023-06-26 03:06
Is it fixed now?

**Comment by owencz1998** [comment] 2023-06-26 06:18
I'll give it ago later dude I think it maybe fixed

**Comment by z-huang** [comment] 2023-06-26 13:36
I need someone to test it out because I don't have a android wear device.

**Comment by owencz1998** [comment] 2023-06-26 16:15
I will do it tonight dude just in my way home from work

**Comment by owencz1998** [comment] 2023-06-28 18:38
@z-huang  I can confirm that I'm seeing the album art on my wear os device and looks beautiful

**Closed** 2023-06-29 03:10 UTC
Labels: bug
