### ISSUE TITLE
Re Artists and Explore and genres sections 

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#755] opened 2023-07-06 13:27 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Artists and Explore and genres sections 

### Why do you want this feature?

Please can you make it possible to add Artists that I like in the artists tab and also add the explore /genres as per the previous version
I also do not tend to use the quick picks section..
Still a fantastic app. Just keen to get the artists issue sorted

**Comment by z-huang** [comment] 2023-07-06 14:22
Duplicate of #712 and #542

They will be added in later versions.

**Closed by z-huang** 2023-07-06 14:22 UTC
Labels: enhancement

**Comment by z-huang** [comment] 2023-07-07 01:55
Thanks! They will take some time to implement, so I plan to release 0.5.0 first. Parsing YouTube's private API responses is a nightmare because they're badly formatted. 😅

**Comment by seasidesongs** [comment] 2023-07-07 14:56
Many thanks
Look forward to it being instigated very soon will then buy you lots more coffees 🤣🤣
