### ISSUE TITLE
Cannot Listen to Surfer Rosa by The Pixies due to album art

### ISSUE THREAD

**Issue by UndeadSlayer836** [z-huang/InnerTune#634] opened 2023-04-04 17:45 UTC
as the title states the album Surfer Rosa by The Pixies is unplayable due to the album art having a photograph of a nude female, I'm simply met with the message "Sign in to confirm your age" over the album cover, but of course Innertune has no sign in feature. This might not be a large problem for most but it seems like a big oversight that any album with risqué art or subject matter might be unlistenable through this app.

**Comment by z-huang** [comment] 2023-06-10 11:12
Duplicate of #644

**Closed by z-huang** 2023-06-10 11:12 UTC
