### ISSUE TITLE
Too much lagging

### ISSUE THREAD

**Issue by someonespcl** [z-huang/InnerTune#748] opened 2023-07-04 20:17 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open and listen to listen after some time it starts lagging

### Expected behavior

App size less by that it should not to lag

### Actual behavior

App lags a lot

### InnerTune version

0.4.4

### Android version

Android 12

**Comment by z-huang** [comment] 2023-07-05 02:38
Duplicate of #734

**Closed by z-huang** 2023-07-05 02:38 UTC
Labels: bug
