### ISSUE TITLE
Add option to choose app language

### ISSUE THREAD

**Issue by Krintni** [z-huang/InnerTune#678] opened 2023-06-17 11:21 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The app should offer an option in the settings under Appearance to change the interface language. In the best case scenario the app uses the system language by default if the appropriate language strings were translated and allows to change the used language in the settings.

### Why do you want this feature?

There are quite a few translated languages that were pushed to the repository and it would be cool to have an option to change the used language to improve the user experience for users that aren't native English speakers or have limited understanding of the English language. While Innertune is still in early development and new strings are being added I believe it's better to have a few missing translations than none at all! :)

**Comment by z-huang** [comment] 2023-06-17 11:30
Duplicate of #250

**Closed by z-huang** 2023-06-17 11:30 UTC
Labels: enhancement
