### ISSUE TITLE
Auto pause/Sleep Timer

### ISSUE THREAD

**Issue by axolotlextnd** [z-huang/InnerTune#674] opened 2023-06-13 15:49 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

timer for stopping music

### Why do you want this feature?

i need this for playing some music before sleeping, so timer is really good

**Comment by owencz1998** [comment] 2023-06-13 16:22
Sleep timer is in the new compose branch download from the actions page via browser.

**Comment by z-huang** [comment] 2023-06-14 06:27
Duplicate of #97

**Closed by z-huang** 2023-06-14 06:27 UTC
Labels: enhancement
