### ISSUE TITLE
Song is not getting added automatically in songs library after when it completes playing 

### ISSUE THREAD

**Issue by sarangwce** [z-huang/InnerTune#693] opened 2023-06-23 04:38 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. play any song and complete it completes it is not getting added in songs library automatically
2. auto add song to library setting is enabled

### Expected behavior

song should be added in song library 

### Actual behavior

song is not getting added 

### InnerTune version

0.4.4 debug

### Android version

13

**Comment by z-huang** [comment] 2023-06-23 08:14
Duplicate of #616

**Closed by z-huang** 2023-06-23 08:14 UTC
Labels: bug
