### ISSUE TITLE
Possibility to edit YT Music account playlists and have played history if logged in

### ISSUE THREAD

**Issue by Gi-R** [z-huang/InnerTune#448] opened 2022-11-28 14:14 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Music history and switch from local to yt music linked sections for playlist, tracks, album and artist if possible

### Why do you want this feature?

To have the history of music played and have updated playlists on yt music without needing the official app or go to the website if logged in

**Comment by z-huang** [comment] 2022-11-28 15:22
I won't provide history from your Google account.
Duplicate of #88

**Closed by z-huang** 2022-11-28 15:22 UTC
Labels: enhancement
