### ISSUE TITLE
Google account support

### ISSUE THREAD

**Issue by Urbexed** [z-huang/InnerTune#670] opened 2023-06-09 04:35 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Be able to connect to your Google account to be able to access your already liked music, playlists and artists 

### Why do you want this feature?

I have hundreds of music I liked on YT music and it's impossible to add everything manually

**Comment by creativetrendsapps** [comment] 2023-06-09 05:25
The reason this app is literally is available is To NOT use a Google account.

**Comment by z-huang** [comment] 2023-06-10 10:42
Duplicate of #88.

**Closed by z-huang** 2023-06-10 10:42 UTC
Labels: enhancement
