### ISSUE TITLE
Playlists stuck

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#575] opened 2023-02-11 12:39 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Na

### Expected behavior

The playlist should play in sequence 

### Actual behavior

The playlist is stuck and does not move into the next track

### Music version

0.4.4

### Android version

Android 12

### Additional information

When I play a playlist it sometimes get stuck when playing the next track

**Comment by z-huang** [comment] 2023-02-14 03:57
Duplicate of #434

**Closed by z-huang** 2023-02-14 03:57 UTC
Labels: bug
