### ISSUE TITLE
Please add A log in function to get Libary to a new device 

### ISSUE THREAD

**Issue by PaLo6415** [z-huang/InnerTune#418] opened 2022-11-06 22:13 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please add a log in function to get Libary to a new device

### Why do you want this feature?

To get Libary of Songs, Artists, Albums & Playlists

### Additional information

Please add it

**Comment by owencz1998** [comment] 2022-11-06 22:22
He's added login on the debug for next release but he's still working on it as I know off

**Comment by z-huang** [comment] 2022-11-06 23:24
Duplicate of #88

**Closed** 2022-11-06 23:24 UTC
Labels: duplicate, enhancement

**Comment by PaLo6415** [comment] 2022-11-06 23:27
Not the same as 88 i meant account for innertune not yt music Account

**Comment by z-huang** [comment] 2022-11-07 01:37
> Not the same as 88 i meant account for innertune not yt music Account

Not possible.

**Comment by PaLo6415** [comment] 2022-11-07 01:49
Okay
