### ISSUE TITLE
Option to play local music from the phone

### ISSUE THREAD

**Issue by Radical4ever** [z-huang/InnerTune#467] opened 2022-12-06 01:34 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The feature would be like an option or another thing on the library section when we could see our local music (and even better we could make mixes with our already downloaded music from innertune)

### Why do you want this feature?

The player from innertune looks better than what i use, and the possibility to have all songs in one app is a very cool thing

### Additional information

I would leave a sreenshoot of what yt music has
![Screenshot_20221205_223054](https://user-images.githubusercontent.com/83252104/205786534-40520c5b-4b52-43f3-9c36-7a2ec19c35d0.png)

**Comment by Radical4ever** [comment] 2022-12-06 01:35
Oh, and i forfot to tell that if its possible to use innertune features on the local musoc files (like lyrics or using local .lrc file)

**Comment by z-huang** [comment] 2022-12-06 02:44
Duplicate of #3

**Closed by z-huang** 2022-12-06 02:44 UTC
Labels: enhancement
