### ISSUE TITLE
Not Been Able to Delete Multiple Songs At once! 

### ISSUE THREAD

**Issue by Vishcot** [z-huang/InnerTune#795] opened 2023-07-10 19:02 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

There is no Multiple Songs Select option 

### Expected behavior

Should highlight songs and select multiple at once for easy delete 

### Actual behavior

Not working!

### InnerTune version

0.5.0

### Android version

Android 14

**Comment by z-huang** [comment] 2023-07-11 02:40
Duplicate of #695

**Closed by z-huang** 2023-07-11 02:40 UTC
Labels: bug
