### ISSUE TITLE
Getting Stacktrace error when trying to download songs

### ISSUE THREAD

**Issue by GiJ03** [z-huang/InnerTune#630] opened 2023-04-01 18:56 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Import the backup.
2. Click on the vertical 3 dots on the "Liked Songs" playlist and click on download.
3. The below error message is observed after that,

![image](https://user-images.githubusercontent.com/57536491/229309169-2a36e4e4-5455-49ba-9f4e-8b211366b2bf.png)

### Expected behavior

I should be able to download all the liked songs.

### Actual behavior

Getting stack trace error

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/57536491/229309216-166f79a4-e011-4eb1-a328-8245fcb0498f.mp4

### Music version

0.4.4

### Android version

Android 13

**Comment by selurvedu** [comment] 2023-05-03 15:42
> - [x] I've checked that there is no issue about this bug.

Duplicate of #551 :)

**Closed** 2023-06-23 11:33 UTC
Labels: bug
