### ISSUE TITLE
Create a Discord server

### ISSUE THREAD

**Issue by candroid-man** [z-huang/InnerTune#458] opened 2022-12-04 05:11 UTC
I want to be able to ask about things without making an issue for it, it would be cool to have a casual conversation with the dev and other users.

If you don't want to use Discord due to privacy concerns, consider Mattermost, Revolt, or Matrix

**Comment by z-huang** [comment] 2022-12-04 07:39
Duplicate of #86

**Closed** 2022-12-04 07:39 UTC
Labels: duplicate
