### ISSUE TITLE
Crash caused by clicking cache on the setting interface

### ISSUE THREAD

**Issue by xiaohu-min** [z-huang/InnerTune#338] opened 2022-10-20 04:08 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/InnerTune/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

After the application is started for the first time, click the cache in the settings to view, which will cause a crash

### Expected behavior

The cache data page should be displayed normally

### Actual behavior

The application crashes after clicking the cache item in the settings list

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/80657533/196853686-edeadcaf-0b54-434c-a37f-6de2e4a6e77d.mp4

### Logs

 java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:84)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.getCacheSpace(SimpleCache.java:354)
        at com.zionhuang.music.ui.fragments.settings.CacheSettingsFragment$serviceConnection$1.onServiceConnected(CacheSettingsFragment.kt:25)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)

### Music version

0.4.2

### Android version

7

**Comment by z-huang** [comment] 2022-10-20 04:27
Duplicate of #315

**Closed** 2022-10-20 04:27 UTC
Labels: bug, duplicate
