### ISSUE TITLE
Add sleep mode like after 10 minutes music stop automatically 

### ISSUE THREAD

**Issue by Darshil-154** [z-huang/InnerTune#483] opened 2022-12-18 17:39 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add sleep mode like aftr 10 minutes or 30 min the music automatically stops

### Why do you want this feature?

For night music listing

**Comment by kach17** [comment] 2022-12-18 18:38
duplicate of #97

**Closed** 2022-12-18 23:22 UTC
Labels: duplicate, enhancement
