### ISSUE TITLE
Better Notification Display/Controls

### ISSUE THREAD

**Issue by SecularSteve** [z-huang/InnerTune#802] opened 2023-07-11 19:00 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Whenever the phone is locked, or the notifications are pulled down, all it gives me is the play/pause button.

No skipping, and no dragging without fully opening the application.

### Why do you want this feature?

So that it's much easier to skip, or go back to songs without going through additional redundant steps for it.

It's for convenience, but it's also merely only a suggestion.

### Additional information

Compare it to ViMusic as a reference example:

![Screenshot_2023-07-11_21-43-59~2](https://github.com/z-huang/InnerTune/assets/33793273/35d6b000-7515-4fb8-8c64-feabd365ea4f)
![Screenshot_2023-07-11_21-44-02~2](https://github.com/z-huang/InnerTune/assets/33793273/4544fe8c-91d2-46e2-a47d-1039faf98e21)
![Screenshot_20230711-215823~2](https://github.com/z-huang/InnerTune/assets/33793273/6e13e5f6-a3be-40fe-b1f9-6d6710ad01be)
![Screenshot_20230711-215826~2](https://github.com/z-huang/InnerTune/assets/33793273/9bb1dc01-d0a0-43a7-8b30-6dc381cf0901)

**Comment by z-huang** [comment] 2023-07-12 04:18
Duplicate of #377

**Closed by z-huang** 2023-07-12 04:18 UTC
Labels: enhancement
