### ISSUE TITLE
We Atleast Require Multiple Select Option TO DELETE SONGS AT ONCE

### ISSUE THREAD

**Issue by Vishcot** [z-huang/InnerTune#861] opened 2023-07-21 10:06 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Multiple select option 

### Expected behavior

It is really tough to delete from 700+ added songs, deleting no more required ones from them on by one! 
Dont give download all feature, its okay! But this is a basic necessity of a player! Please 🙏🏻 understand, a humble request 🙏🏻

### Actual behavior

It doesn't have this for now

### InnerTune version

0.5.0 debug

### Android version

Android 14

**Comment by z-huang** [comment] 2023-07-21 10:28
Duplicate of #695

**Closed by z-huang** 2023-07-21 10:28 UTC
Labels: bug
