### ISSUE TITLE
Crash on cache screen

### ISSUE THREAD

**Issue by tarunbuddy** [z-huang/InnerTune#346] opened 2022-10-22 13:20 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/InnerTune/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to settings
2. Click on the cache option 

### Expected behavior

It should take you to the cache screen without crash.

### Actual behavior

App crashes everytime on clicking the cache option after it navigates to the screen.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/39480406/197341268-6ab347f6-eb63-4439-a6a5-549df0465ab3.mp4

### Music version

"0.4.2"

### Android version

Android 12

**Comment by z-huang** [comment] 2022-10-22 13:58
Duplicate of #315

**Closed by z-huang** 2022-10-22 13:58 UTC
Labels: bug
