### ISSUE TITLE
When playing song it shows "2nR1zrNzgcY: open failed: ENOENT (No such file or directory)"

### ISSUE THREAD

**Issue by dainvincible1** [z-huang/InnerTune#964] opened 2023-08-11 16:19 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to travis scott then go to album "uthopia" play "fe!n", the song stops exactly at 2.05 every time. 

### Expected behavior

It should play the full song

### Actual behavior

The song stops midway

### Screenshots/Screen recordings

![image](https://github.com/z-huang/InnerTune/assets/127825700/4e4b0dc1-577c-4433-9173-675a21f95336)

### InnerTune version

0.5.1

### Android version

11

**Comment by unseenlarks** [comment] 2023-08-14 00:21
adding a 'me too'. happened several times (different songs, not the above) today.

**Comment by Kurasami** [comment] 2023-08-15 19:37
This error happens on an unstable connection. I've played this song a few times myself and thousands more without seeing this error. Try downloading songs first before playing them if your connection is unstable.

**Comment by dainvincible1** [comment] 2023-08-16 04:51
> This error happens on an unstable connection. I've played this song a few times myself and thousands more without seeing this error. Try downloading songs first before playing them if your connection is unstable.

@Kurasami  if the connection was unstable would it not effect other songs too? moreover there is a cache feature. if once i play the song, then i can play it offline without downloading, so it shouldn't be effected even if the connection is unstable maybe

**Comment by owencz1998** [comment] 2023-08-16 06:14
This could also be if you had the previous version going back to 0.4.0 it maybe due to it being downloaded song but when updating to 0.5.0 or 0.5.1 this can cause the issue try downloading the old version remove download then update app then try to play and download again.

**Comment by dainvincible1** [comment] 2023-08-16 06:37
> This could also be if you had the previous version going back to 0.4.0 it maybe due to it being downloaded song but when updating to 0.5.0 or 0.5.1 this can cause the issue try downloading the old version remove download then update app then try to play and download again.

i never had any song downloaded, i just add it to library

**Comment by owencz1998** [comment] 2023-08-16 10:37
No worries u tried clearing cache also force close it 1st

**Comment by z-huang** [comment] 2023-08-27 02:20
Duplicate of #856
Fixed.

**Closed by z-huang** 2023-08-27 02:20 UTC
Labels: bug
