### ISSUE TITLE
Could you please make this app play ANY track?

### ISSUE THREAD

**Issue by AlexIs387** [z-huang/InnerTune#918] opened 2023-08-03 01:42 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Error when playing some tracks

### Expected behavior

Play all the tracks without any error

### Actual behavior

Error when playing some tracks

### Screenshots/Screen recordings

![Screenshot_20230802-202807](https://github.com/z-huang/InnerTune/assets/131836904/179c2cd4-2444-4b13-89d8-e480b2b167b4)

### InnerTune version

0.5.0

### Android version

Android 7

**Comment by z-huang** [comment] 2023-08-03 03:47
Duplicate of #856

**Closed by z-huang** 2023-08-03 03:47 UTC
Labels: bug
