### ISSUE TITLE
Explore and search not working

### ISSUE THREAD

**Issue by Ramnita331** [z-huang/InnerTune#534] opened 2023-01-24 22:29 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open the app

### Expected behavior

I dont really know

### Actual behavior

I dont really know

### Logs

vb.d: Field 'contents' is required for type with serial name 'com.zionhuang.innertube.models.response.BrowseResponse.ContinuationContents.SectionListContinuation', but it was missing at path: $.continuationContents.sectionListContinuation at path: $.continuationContents.sectionListContinuation at path: $.continuationContents.sectionListContinuation
	at ac.w.M(SourceFile:110)
	at zb.a.b(SourceFile:25)
	at aa.c.a(SourceFile:105)
	at aa.c$a.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)
Caused by: vb.d: Field 'contents' is required for type with serial name 'com.zionhuang.innertube.models.response.BrowseResponse.ContinuationContents.SectionListContinuation', but it was missing at path: $.continuationContents.sectionListContinuation at path: $.continuationContents.sectionListContinuation
	at ac.w.M(SourceFile:110)
	at androidx.fragment.app.z.z0(Unknown Source:27)
	at com.zionhuang.innertube.models.response.BrowseResponse$a.e(SourceFile:83)
	at ac.w.M(SourceFile:68)
	... 8 more
Caused by: vb.d: Field 'contents' is required for type with serial name 'com.zionhuang.innertube.models.response.BrowseResponse.ContinuationContents.SectionListContinuation', but it was missing at path: $.continuationContents.sectionListContinuation
	at ac.w.M(SourceFile:110)
	at androidx.fragment.app.z.z0(Unknown Source:27)
	at com.zionhuang.innertube.models.response.BrowseResponse$ContinuationContents$a.e(SourceFile:51)
	at ac.w.M(SourceFile:68)
	... 11 more
Caused by: vb.d: Field 'contents' is required for type with serial name 'com.zionhuang.innertube.models.response.BrowseResponse.ContinuationContents.SectionListContinuation', but it was missing
	at nb.d.r(SourceFile:108)
	at com.zionhuang.innertube.models.response.BrowseResponse$ContinuationContents$SectionListContinuation.<init>(SourceFile:16)
	at com.zionhuang.innertube.models.response.BrowseResponse$ContinuationContents$SectionListContinuation$a.e(SourceFile:79)
	at ac.w.M(SourceFile:68)
	... 14 more

### Music version

0.4.4

### Android version

Android 12

### Additional information

none

**Comment by z-huang** [comment] 2023-01-25 05:43
Duplicate of #535

**Closed by z-huang** 2023-01-25 05:43 UTC
Labels: bug
