### ISSUE TITLE
java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicResponsiveListItemRenderer.c(SourceFile:911)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:228)
	at x7.h.m(SourceFile:179)
	at x7.h$j.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)


### ISSUE THREAD

**Issue by Vkbhai** [z-huang/InnerTune#631] opened 2023-04-01 20:19 UTC

**Comment by itsmmt305** [comment] 2023-04-02 06:24
well organized man. nice!

**Comment by EisregenHoho** [comment] 2023-04-09 00:38
> well organized man. nice!

Right? We can definitely see whats going on here and what the problem is! The description is so detailed too, beautiful. I bet this is the reason the dev isnt as active anymore, really sad, he prolly got annoyed by the countless weird open issues and requests. Man im sad bout the inactivity recently

**Comment by fbievan** [comment] 2023-04-14 11:16
Someone with write acess should close this  as this is not experinced on debug builds

I have the same error though. 

**Please close this** for the sake of everyone

**Closed** 2023-04-15 11:23 UTC
