### ISSUE TITLE
Log in YouTube Music

### ISSUE THREAD

**Issue by max5354** [z-huang/InnerTune#88] opened 2022-06-09 07:39 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

it will be great if you add log in or sign in option with gmail.

### Why do you want this feature?

It's necessary

**Comment by z-huang** [comment] 2022-06-09 07:56
What do you expect to benefit if you can log in with Gmail?

**Comment by XRedCubeX** [comment] 2022-06-10 08:47
> What do you expect to benefit if you can log in with Gmail?

Import Playlists from google accounts and always have them synchronized between devices or in case you format the device

**Comment by proItheus** [comment] 2022-06-14 03:25
> > What do you expect to benefit if you can log in with Gmail?
> 
> Import Playlists from google accounts and always have them synchronized between devices or in case you format the device

I think simple log in to google account may not be the right approach to do this due to  
> this data octopus

and adding google libraries , which are proprietary, will cause this app to be not fully FOSS, thus cant be accessed by fdroid.

I think maybe it's better to add an option to storage (or  regularly sync) playlists to some public storage area , like Musics/playlists/playlistname.m3u8, and use tools like [syncthing](https://syncthing.net/) to sync it among devices. Or maybe store it to nextcloud ?

For export existing playlists in YTM, maybe something like [youtube-dl](https://github.com/ytdl-org/youtube-dl) can help.

**Comment by IceDBorn** [comment] 2022-06-14 04:26
What about using Piped for playlists etc? @z-huang

**Comment by ArjixWasTaken** [comment] 2022-08-16 02:15
You can login with a Google account without using a google library, I don't see how this is an issue.

An easy way would be to use a WebView to login, and then grab the cookies.

But that way requires that you mimic the web client for yt music...

**Comment by z-huang** [comment] 2022-08-16 02:45
> An easy way would be to use a WebView to login, and then grab the cookies.

 That's the solution I'm thinking.

> But that way requires that you mimic the web client for yt music...

I'm already doing this.

**Comment by nikhilCad** [comment] 2022-08-16 03:18
Don't sign in into apps that violate Google's TOS like this one

**Comment by z-huang** [comment] 2022-08-16 04:01
It's just mimicking what YT is doing.

**Comment by dotmashrc** [comment] 2022-10-30 18:25
> What do you expect to benefit if you can log in with Gmail?

it will make migration (slightly) easier for those who are using yt music

like i couldn't import my replay mix and other profile specific playlists which was one of the biggest reasons i was so uncomfortable with the thought of moving to a different music player from yt music

**Comment by nikhilCad** [comment] 2022-10-30 18:28
Doesn't Newpipe have an option to import from Google takeout? Maybe something similar can be done here without adding log in/sign in

**Comment by ArjixWasTaken** [comment] 2022-10-30 20:30
> Doesn't Newpipe have an option to import from Google takeout? Maybe something similar can be done here without adding log in/sign in

Well, considering that you can make your playlist public, and after a day or two it will be discoverable just by searching the playlist's name
(why am i mentioning searching the playlist instead of just using a link? because i cant use the link via InnerTube..., so searching is the only way)

you can kinda already view your music in this app, the issue is that you can't import a playlist, and you cant batch add songs to a playlist...

so if you have like 400 songs in a playlist, you are done for...

**Comment by nikhilCad** [comment] 2022-10-31 02:02
So looks like the solution is adding a way to open public playlists via links

**Comment by z-huang** [comment] 2022-10-31 05:24
@ArjixWasTaken Why can't you open link via InnerTune? And why can't you batch add songs to a playlist? These are already supported.

**Comment by ArjixWasTaken** [comment] 2022-10-31 06:48
> @ArjixWasTaken Why can't you open link via InnerTune? And why can't you batch add songs to a playlist? These are already supported.

I haven't used the app for like 2 months now, so I apologize for not knowing that you added those features.

**Comment by ArjixWasTaken** [comment] 2022-11-01 22:05
> > @ArjixWasTaken Why can't you open link via InnerTune? And why can't you batch add songs to a playlist? These are already supported.
> 
> I haven't used the app for like 2 months now, so I apologize for not knowing that you added those features.

Lmao, actually no, you have added the feature to import a playlist, yes, but only from the search results...if you open a playlist using the link then...you are fucked

**Comment by z-huang** [comment] 2022-11-02 00:31
Yes, #260 is not implemented yet. But you can select multiple songs and add them to playlist.

**Comment by thangisme** [comment] 2022-11-03 06:08
Hi, I'd like this feature as well since I could get personal tailored recommendations.

**Comment by z-huang** [comment] 2022-11-03 06:24
I'm working on this recently since I discovered YouTube removed search suggestions for users who don't log in.

**Comment by z-huang** [comment] 2022-11-03 13:56
Now you can login from Settings->Content->Login. Search suggestion works again.
However, the feed in the home page will be the same if you only use InnerTune, for InnerTune doesn't send your playing history back to YouTube.

**Comment by NeeRaj-2401** [comment] 2022-11-03 14:10
> Since I don't have YouTube Premium, I need someone to test if high quality streams are available after logged in.

Test using Revanced YTM which unlocks morecodecs / high quality...

**Comment by z-huang** [comment] 2022-11-03 15:45
Though there isn't a button to view your account's playlists, some of them can be found in the home page.

**Comment by XRedCubeX** [comment] 2022-11-03 15:52
> Though there isn't a button to view your account's playlists, some of them can be found in the home page. I'm still thinking how to make a better integration with Google accounts.

Ok, thanks for the work and have a nice day.

**Comment by max5354** [comment] 2022-11-04 13:46
> Now you can login from Settings->Content->Login. Search suggestion works again. However, the feed in the home page will be the same if you only use InnerTune, for InnerTune doesn't send your playing history back to YouTube.
> 
> Since I don't have YouTube Premium, I need someone to test if high quality streams are available after logged in.
> 
> Note: InnerTune provides a webview for you to log in, and the only thing InnerTune does is to save the cookies so as to make authenticated requests to YouTube Music. You can log out by entering the webview and log out. Your password will NEVER be saved. Feel free to experience the feature!

Yes!!! YouTube music revanced has option "always high quality" option. That means we can get higher quality songs without paying single penny.

**Comment by z-huang** [comment] 2022-11-04 13:49
Only when you are logged in with a PREMIUM account will you be possible to get streams with bitrate >200 kbps. I want people to test if this is true in InnerTune.

**Comment by max5354** [comment] 2022-11-04 14:21
> Only when you are logged in with a PREMIUM account will you be possible to get streams with bitrate >200 kbps. I want people to test if this is true in InnerTune.

I don't have premium account and youtube premium. Just have youtube revanced music. And still got high quality audio. I listened songs with both option "low and high". I really see difference between those two option.

**Comment by z-huang** [comment] 2022-11-04 14:31
What's the bitrate when you use YouTube reVanced with high quality option?

**Comment by max5354** [comment] 2022-11-04 14:46
> What's the bitrate when you use YouTube reVanced with high quality option?

256kbps.

**Comment by ArjixWasTaken** [comment] 2022-11-04 15:18
> > Now you can login from Settings->Content->Login. Search suggestion works again. However, the feed in the home page will be the same if you only use InnerTune, for InnerTune doesn't send your playing history back to YouTube.
> > Since I don't have YouTube Premium, I need someone to test if high quality streams are available after logged in.
> > Note: InnerTune provides a webview for you to log in, and the only thing InnerTune does is to save the cookies so as to make authenticated requests to YouTube Music. You can log out by entering the webview and log out. Your password will NEVER be saved. Feel free to experience the feature!
> 
> Yes!!! YouTube music revanced has option "always high quality" option. That means we can get higher quality songs without paying single penny.

less gooo, guess I gotta update it to get that patch!

**Comment by z-huang** [comment] 2022-11-04 15:23
@max5354 However, in my phone, almost every song comes with itag 251 when I use high quality option, and itag 251 doesn't have bitrate over 200kbps. Can you share your screenshot with stats for nerds?

**Comment by thangisme** [comment] 2022-11-06 12:36
> Now you can login from Settings->Content->Login. Search suggestion works again. However, the suggestions in the home page will be the same if you only use InnerTune, for InnerTune doesn't send your playing history back to YouTube.
> 
> Though theorically we can do almost everything YTM can do after logged in, I only plan for these features:
> 
>     1. Make search suggestion working
> 
>     2. Make migration from your Google account to InnerTune easier
> 
> 
> As for personal music suggestions, I plan to redesign the home tab to make it more useful.
> 
> _Since I don't have YouTube Premium, I need someone to test if high quality streams (>200 kbps) are available after logged in._
> 
> Note: InnerTune provides a webview for you to log in, and the only thing InnerTune does is to save the cookies so as to make authenticated requests to YouTube Music. You can log out by entering the webview and log out. Your password will NEVER be saved. Feel free to experience the feature!

Awesome! Would it is possible to also get liked song from Youtube Music and like song on the app also add it to yt music?

**Comment by z-huang** [comment] 2022-11-06 13:03
Yes, it's possible.

**Comment by owencz1998** [comment] 2022-11-06 14:48
Would u add the login to the home screen at the top and once you have added your account it will switch to your profile picture and if u click it again it will show option to logout

**Comment by z-huang** [comment] 2022-11-12 07:35
@owencz1998 Something like this?
![IMG_20221112_153407.jpg](https://user-images.githubusercontent.com/39427017/201463049-03442018-146c-4a42-8275-6a410b41ed6d.jpg)

**Comment by owencz1998** [comment] 2022-11-12 08:48
Yes dude 🙂

**Comment by LuanRT** [comment] 2022-11-12 23:21
> Since I don't have YouTube Premium, I need someone to test if high quality streams (>200 kbps) are available after logged in.

Great job @z-huang. I have YouTube Premium and once logged in it defaulted to the highest quality (itag 141). 

Also, do you plan on implementing history? Now that login is available you could use YouTube's own history system for those who want to have their library synced — you'd have to implement playback tracking (a single call to the initialization endpoint would do) but it is relatively simple.

**Comment by LuanRT** [comment] 2022-11-12 23:24
> > Now you can login from Settings->Content->Login. Search suggestion works again. However, the feed in the home page will be the same if you only use InnerTune, for InnerTune doesn't send your playing history back to YouTube.
> > Since I don't have YouTube Premium, I need someone to test if high quality streams are available after logged in.
> > Note: InnerTune provides a webview for you to log in, and the only thing InnerTune does is to save the cookies so as to make authenticated requests to YouTube Music. You can log out by entering the webview and log out. Your password will NEVER be saved. Feel free to experience the feature!
> 
> Yes!!! YouTube music revanced has option "always high quality" option. That means we can get higher quality songs without paying single penny.

ReVanced does a few tricks to improve audio quality, it doesn't actually fetch the highest quality stream (it is a server side thing).

**Comment by z-huang** [comment] 2022-11-14 03:09
I'm not inclined to implement YouTube's history, for privacy issues. I don't want to pollute my YouTube history. Instead, I would record history locally, and it will be more flexible to manage the history. (I can add batch operation.)

**Comment by NeeRaj-2401** [comment] 2022-11-14 07:15
> I would record history locally

YouTube's history are used in better recommendations.. 

So if u r not  planning to implement that .... i don't think there is much need for history locally...  For that u already have implemented **add to library** etc. features to store the list of songs

**Comment by Alliba** [comment] 2022-11-14 07:58
> > I would record history locally
> 
> YouTube's history are used in better recommendations..
> 
> So if u r not planning to implement that .... i don't think there is much need for history locally... For that we already have **add to library** etc. features to store the list of songs

I would find storing the history locally privacy friendly and user compfor.  Please implement.

**Comment by Alliba** [comment] 2022-11-14 08:58
> 

I would find storing the history locally privacy friendly and user compfor.  Please implement.

**Comment by Alliba** [comment] 2022-11-14 09:00
> I'm not inclined to implement YouTube's history, for privacy issues. I don't want to pollute my YouTube history. Instead, I would record history locally, and it will be more flexible to manage the history. (I can add batch operation.)

This variant sounds very good.

**Comment by z-huang** [comment] 2022-11-14 09:02
@NeeRaj-2401 As I said [here](https://github.com/z-huang/InnerTune/issues/88#issuecomment-1302152845), I don't plan to use YouTube's recommendation. That'll make the app too reliant on YouTube and the Google account. Also, history and library are two things. You use history to find what you've listened to, and library to store what you like.

**Comment by candroid-man** [comment] 2022-11-22 06:53
Just here to express support for this feature. Once you are able to login to YouTube Music, I can have all of my music synced to my desktop client as well and have my music wherever I go in a more private way! Very excited for this feature to roll out

**Comment by z-huang** [comment] 2022-11-22 06:59
Since suggestion feature is given back by YouTube, I'll postpone login feature until 0.5.0 (#421).

**Comment by tokenwizard** [comment] 2023-01-12 15:14
> > Doesn't Newpipe have an option to import from Google takeout? Maybe something similar can be done here without adding log in/sign in
> 
> Well, considering that you can make your playlist public, and after a day or two it will be discoverable just by searching the playlist's name (why am i mentioning searching the playlist instead of just using a link? because i cant use the link via InnerTune..., so searching is the only way)
> 
> you can kinda already view your music in this app, the issue is that you can't import a playlist, and you cant batch add songs to a playlist...
> 
> so if you have like 400 songs in a playlist, you are done for...

I get this, but I have a public playlist called "'Merica" (a 4th of July Playlist). 
Try searching for that and see how many results come up. this is a common theme for playlist that are not named in a super unique way. 

I like the NewPipe reference and that type of import functionality is exactly what I'm looking for, just in a music-centric app.

**Comment by ArjixWasTaken** [comment] 2023-01-12 18:57
> Try searching for that and see how many results come up. this is a common theme for playlist that are not named in a super unique way.

Well, you can always rename the playlist to smth unique, and wait for a few hours so the google servers update the name

**Comment by tokenwizard** [comment] 2023-01-12 19:14
> > Try searching for that and see how many results come up. this is a common theme for playlist that are not named in a super unique way.
> 
> Well, you can always rename the playlist to smth unique, and wait for a few hours so the google servers update the name

True,
But sticking to what seems to be the gist of this Enhancement/Feature request, we could have a way to import all of our playlists at once from a YT Music export. I, personally, have dozens, and once I get them into a third-party app that allows me to listen without logging into a Google Account, that would allow me (and others) to use this as an option on a de-Googled phone running LineageOS or other FOSS options.

**Comment by owencz1998** [comment] 2023-06-27 11:36
@z-huang is login still going to be added at some point as would be good for using this app cross devices no rush obviously just asking :)

**Closed** 2023-07-15 04:23 UTC
Labels: enhancement

**Comment by z-huang** [comment] 2023-07-15 04:24
Since you can log in your Google account and import your playlists, I think we don't need "import from Google Takeout" (#516).

**Comment by demirdegerli** [comment] 2023-07-19 13:12
@z-huang Will we be able to edit the playlist or add songs to the account playlist? I'm running the debug now.

**Comment by z-huang** [comment] 2023-07-21 03:40
Not planned.

**Comment by decipher3114** [comment] 2023-07-21 16:43
> Since you can log in your Google account and import your playlists, I think we don't need "import from Google Takeout" (#516).

I am not seeing any such option to login to google.

**Comment by demirdegerli** [comment] 2023-07-21 16:45
Because it's not in the latest release, you can build the app yourself if you are curious like me.

**Comment by ArjixWasTaken** [comment] 2023-07-21 17:06
> Because it's not in the latest release, you can build the app yourself if you are curious like me.

meanwhile there are nightly builds

https://github.com/z-huang/InnerTune/suites/14467895105/artifacts/817231369

**Comment by demirdegerli** [comment] 2023-07-21 17:08
I looked up for nightly builds 2 days ago but I couldn't find them. Thanks!

**Comment by decipher3114** [comment] 2023-07-21 17:09
These are in the actions tab 😂😂

**Comment by demirdegerli** [comment] 2023-07-21 17:13
Yes I found them in the artifacts section
