### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by heyoferu** [z-huang/InnerTune#730] opened 2023-07-01 11:33 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I apologize, but it's not a feature request. I've checked how  to contact you and I didn't get a indicated form (email or support group). So, I thought this is the appropriate channel to notice you.

There is an app available on Google Play Store named "Max Music Player" and it's the same application.

https://play.google.com/store/apps/details?id=com.zionhuang.music

![Screenshot_2023-07-01-05-19-09-621_com android vending-edit](https://github.com/z-huang/InnerTune/assets/105750258/b4cdf903-3712-461c-9f4e-aee554b425c6)
![Screenshot_2023-07-01-05-19-23-982_com android vending-edit](https://github.com/z-huang/InnerTune/assets/105750258/14f125a8-c0cc-4b67-bd3b-39d90e59f5f1)

### Why do you want this feature?

.

**Comment by rickdtc** [comment] 2023-07-01 13:58
We know

**Comment by z-huang** [comment] 2023-07-01 15:54
Duplicate of #610

**Closed by z-huang** 2023-07-01 15:54 UTC
Labels: enhancement
