### ISSUE TITLE
Artist Page and Song Information not loading in FOSS Debug Build for songs

### ISSUE THREAD

**Issue by impin2rex** [z-huang/InnerTune#1007] opened 2023-08-27 22:55 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Launch the FOSS Debug Build application.
2. Use the search bar or menu to either perform a search for a song or directly click to play any song that leads to accessing the artist's page.
3. Note that upon accessing the artist's page, the page does not load as expected. Instead, it shows a shimmer effect, which persists indefinitely without displaying the actual content.

### Expected behavior

Upon opening the FOSS Debug Build application and accessing the artist's page for a song, the content should load promptly, displaying relevant artist and song information.

### Actual behavior

After following the provided steps and accessing the artist's page, the expected content does not load. Instead, a shimmer effect is displayed, which continues indefinitely without transitioning to display the actual artist and song information.

### InnerTune version

Latest Debug Version from `dev` branch.

### Android version

Android 13

**Comment by DrRenardScD** [comment] 2023-08-28 21:31
I'm also having this issue on full. I moved to full thinking that it would be fixed with it being straight from github and also being newer version than on fdroid. Artist section has been shimmering for years for me

**Comment by z-huang** [comment] 2023-08-29 06:20
Duplicate of #982

**Closed by z-huang** 2023-08-29 06:20 UTC
Labels: bug
