### ISSUE TITLE
App auto starting when bluetooth is turned

### ISSUE THREAD

**Issue by W1zardK1ng** [z-huang/InnerTune#716] opened 2023-06-29 05:33 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play a song and pause it
Force close the app
turn on the bluetooth, the app will start automatically and shows the song in notifications

### Expected behavior

while turning on the bluetooth, the app should start automatically and shows the song in notifications

### Actual behavior

even if i Force Stop the app, when i turn on Bluetooth (without even connecting to a device) the app is starting and showing the current playing item in the media control area.

### InnerTune version

0.4.4

### Android version

Android 13

### Additional information

even if i Force Stop the app, when i turn on Bluetooth (without even connecting to a device) the app is starting and showing the current playing item in the media control area. This is very annoying since i have to force stop the app every time i turn on the bluetooth but i don't want the media controls there.

Please fix this issue.

**Comment by owencz1998** [comment] 2023-06-29 06:54
Turn off setting in android auto, auto play

**Comment by z-huang** [comment] 2023-06-29 08:13
Duplicate of #433

**Closed** 2023-06-29 08:14 UTC
Labels: bug
