### ISSUE TITLE
Increase bitrate of songs 

### ISSUE THREAD

**Issue by max5354** [z-huang/InnerTune#557] opened 2023-02-04 15:40 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

It will be great if you increase bitrate of songs. The "high" option provides 148kbps. So it will he great if you use high quality 256kbps audio. Vimusic and blackhole uses 256kbps audio for free. Than you can copy and paste code in this app.

### Why do you want this feature?

It will increase audio listening experience

**Comment by z-huang** [comment] 2023-02-04 16:03
Duplicate of #110

**Closed by z-huang** 2023-02-04 16:03 UTC
Labels: enhancement
