### ISSUE TITLE
Can't download "Liked titles"

### ISSUE THREAD

**Issue by Qyuzux** [z-huang/InnerTune#642] opened 2023-04-11 09:32 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to "Playlists"
2. Click on the 3 dots for the "Liked Titles" Playlist.
3. Click "Download" in the context menu.
4. The error shows

### Expected behavior

This should download all the titles from that Playlist.

### Actual behavior

An error screen shows the error.

### Screenshots/Screen recordings

https://gofile.io/d/qpcvop

### Logs

```
java.lang.UnsupportedOperationException
	at k8.g.u(Unknown Source:5)
	at k8.g.e(SourceFile:10)
	at z8.t.u(SourceFile:58)
	at va.a.m(Unknown Source:8)
	at lb.n0.run(Unknown Source:100)
	at rb.a$a.run(SourceFile:82)

```

### Music version

0.4.4

### Android version

Android 12

**Comment by selurvedu** [comment] 2023-05-03 15:42
> - [x] I've checked that there is no issue about this bug.

Duplicate of #630 and #551 :)

**Closed** 2023-06-23 11:32 UTC
Labels: bug
