### ISSUE TITLE
Back and forward buttons on lock screen

### ISSUE THREAD

**Issue by Brtnnr** [z-huang/InnerTune#498] opened 2023-01-05 15:27 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I realy appreciate your work. Love to play music with innertune. The only thing i need to use so far is " back and next" song buttons on lock screen. .

### Why do you want this feature?

Whenever i want to play next song or previous song, i have to open innertune main screen. This feature would be very nice.. Thats all. Thank you for the app

**Comment by z-huang** [comment] 2023-01-06 03:14
Duplicate of #377

**Closed by z-huang** 2023-01-06 03:14 UTC
Labels: enhancement
