### ISSUE TITLE
"Add to library" option directly in opened playlist menu

### ISSUE THREAD

**Issue by ccrowles** [z-huang/InnerTune#437] opened 2022-11-22 12:45 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

As per title, it would be nice to be able to have an "add to library" option inside the playlist menu.

![Screenshot_20221122-132658_InnerTune_1](https://user-images.githubusercontent.com/12866474/203313827-3a4bbf14-b126-4327-9a19-b2133bcfe7ab.jpg)

### Why do you want this feature?

Because currently when you share a playlist from the YouTube app to Innertune, it opens up the playlist menu. Which doesn't have any option (aside from going to Settings).
![Screenshot_20221122-130127_InnerTune](https://user-images.githubusercontent.com/12866474/203315705-07c9d8c9-b4b7-4e0a-bed4-b7e7adf39c40.jpg)

The only current way in the playlist menu to obtain the list is to multiple select all the songs (300+ in my case) by holding and scrolling ([which is quite buggy](https://drive.google.com/file/d/1LzllBZYmNWO4qHvF8cYKM62XkLhzG-Do/view?usp=drivesdk)  and it often deselects after 200 or so, for me, unless I scroll slowly).

But by doing that you're not adding to library the whole playlist, but individual songs, and so it won't be updated when the actual playlist gets updated.

**Comment by z-huang** [comment] 2022-11-27 03:44
Duplicate of #260

**Closed by z-huang** 2022-11-27 03:44 UTC
Labels: enhancement
