### ISSUE TITLE
problem with tabs after a search

### ISSUE THREAD

**Issue by Robinhoods66** [z-huang/InnerTune#493] opened 2023-01-03 11:38 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I do any research and when I navigate in the songs, videos, album tabs, ... it's empty

### Expected behavior

all the time

### Actual behavior

all the time

### Screenshots/Screen recordings

![Screenshot_2023-01-03-12-27-58-382_com zionhuang music](https://user-images.githubusercontent.com/113288892/210349648-aa0d11b7-cafb-41a3-87b2-b450201dc103.jpg)

### Music version

0.4.4

### Android version

A12

**Comment by z-huang** [comment] 2023-01-03 11:41
Is YouTube Music supported in your country?

**Comment by Robinhoods66** [comment] 2023-01-03 11:45
yes i live in france

**Comment by Robinhoods66** [comment] 2023-01-03 11:49
apart from that the app is really great, congratulations for the work

**Comment by z-huang** [comment] 2023-02-05 09:52
Duplicate of #530

**Closed by z-huang** 2023-02-05 09:52 UTC
Labels: bug
