### ISSUE TITLE
Write ID3 tags to local files

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#330] opened 2022-10-18 06:32 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I want these tags (such as artist name, song name, album name, etc.) to be saved in the song file.

### Why do you want this feature?

Maybe I want to add a song to the phone's music player or share it with someone, in any case, ID3 tags are required.

![Screenshot_2022-10-18-09-59-16-512_code name monkey retromusic](https://user-images.githubusercontent.com/23485114/196352749-87365bab-e634-45db-b967-09fa791cccf6.jpg)

![IMG_20221018_095754_832](https://user-images.githubusercontent.com/23485114/196352426-097dcd91-4a51-48b1-9058-7112ca228004.jpg)

**Comment by z-huang** [comment] 2022-10-18 07:59
Duplicate of #117. It can be solved by #117.

**Closed by z-huang** 2022-10-18 07:59 UTC
Labels: enhancement

**Comment by selurvedu** [comment] 2023-05-03 15:17
Relevant: https://github.com/z-huang/InnerTune/issues/117#issuecomment-1533226300
