### ISSUE TITLE
Album tab

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#541] opened 2023-01-29 22:16 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Is it possible to have a section on the three dots tab in the album library that says download and let's you  download the album?? 

### Why do you want this feature?

Easier to download albums if only saved in the the albums library but not downloaded

**Comment by z-huang** [comment] 2023-01-30 06:33
Duplicate of #520?

**Comment by seasidesongs** [comment] 2023-01-30 07:09
Hi. This is different because it is regarding a section on the the dots in the album section. Hopefully this can be instigated. Keep up the great work 👍👍

**Comment by z-huang** [comment] 2023-02-09 13:34
#520 will be enough. Also, in 0.5.0 (#421), there's a search bar instead of a top app bar in top level destinations, so there won't be menu button.

**Closed by z-huang** 2023-02-09 13:34 UTC
Labels: enhancement
