### ISSUE TITLE
Notification shows extremely low quality Album cover

### ISSUE THREAD

**Issue by Vishcot** [z-huang/InnerTune#680] opened 2023-06-17 14:27 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play song
2. See notification 

### Expected behavior

Notification should be low quality 

### Actual behavior

Notification should be at higher resolution similar to other streaming platforms 

### Screenshots/Screen recordings

![Screenshot_20230617-195436](https://github.com/z-huang/InnerTune/assets/136909951/c441458c-0082-4203-90b8-8b6304ead5a2)
![Screenshot_20230617-195423](https://github.com/z-huang/InnerTune/assets/136909951/511ae914-03e5-465f-977f-06d93df5c86f)

### InnerTune version

0.4.4

### Android version

Android 14

### Additional information

Please fix this error..if it can be possible 🙏🏻

**Comment by z-huang** [comment] 2023-06-20 10:12
Duplicate of #244

**Closed by z-huang** 2023-06-20 10:12 UTC
Labels: bug
