### ISSUE TITLE
Improve notification style

### ISSUE THREAD

**Issue by dotmashrc** [z-huang/InnerTune#377] opened 2022-10-30 18:36 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

i would like to be able to navigate through my song queue using the notification

### Why do you want this feature?

it is a pretty standard feature in most music players and it's just convenient to be able to skip songs without having to open the app

### Additional information

something like these would be good
![example image from blackhole](https://user-images.githubusercontent.com/90378831/198895567-8d3b8828-f57d-47ae-9b54-51c3b18e6188.jpg)

**Comment by z-huang** [comment] 2022-10-30 23:26
It already exists. What's your Android version? Can you provide a screenshot?

**Comment by owencz1998** [comment] 2022-10-31 06:51
That's all I get on the samsung lock screen mate 

![Screenshot_20221031_065007_One UI Home.jpg](https://user-images.githubusercontent.com/96526481/198948463-af6c9eef-4c27-4ba2-89f8-99dcff701250.jpg)

**Comment by owencz1998** [comment] 2022-10-31 06:58
When phone is unlocked it shows like this but when expanded it shows not sure if u can make it so u don't need to expanded the notification dude 


![Screenshot_20221031_065629_GitHub.jpg](https://user-images.githubusercontent.com/96526481/198949510-a1f41a9c-5b55-4544-bb19-fba55cd41034.jpg)


![Screenshot_20221031_065631_GitHub.jpg](https://user-images.githubusercontent.com/96526481/198949532-aa0b6dcb-0ee2-4596-9e63-fdaf1122760e.jpg)

**Comment by z-huang** [comment] 2022-10-31 08:42
In my phone I don't need to expand it, so I think it's due to the phone manufacturer.
<img src="https://user-images.githubusercontent.com/39427017/198966944-a3b16127-3bec-4c39-b342-2e4aec0e56b7.jpg" width=200 />

**Comment by dotmashrc** [comment] 2022-10-31 13:48
> What's your Android version?
i have android version 12 though i run realme ui 
![and some extra info](https://user-images.githubusercontent.com/90378831/199022089-4307d2be-4d98-4f57-88a7-0dd679361502.jpg)

**Comment by dotmashrc** [comment] 2022-10-31 13:51
like @owencz1998 said i too can only find the navigation options on expanding the notification 
![expanded notif](https://user-images.githubusercontent.com/90378831/199023396-1334881b-f83c-4930-b673-d9e17f1bcd37.jpg)

i will check if this is the case with older versions as well

**Comment by owencz1998** [comment] 2022-10-31 13:59
Yeah I'm sure before u used to have the navigation but there's literally nothing on the lockscreen used pause and play no expanding on the lockscreen to

**Comment by dotmashrc** [comment] 2022-10-31 14:08
i checked the following versions and none of them work on my device
- 0.3.0
- 0.3.1
- 0.3.2
- 0.3.3
- 0.4.0
- 0.4.1
- 0.4.2

**Comment by owencz1998** [comment] 2022-10-31 14:09
Ahh I thought there was a version is there away to make a separate type for the samsungs

**Comment by z-huang** [comment] 2022-10-31 14:22
I tried in Android 12 emulator. Just as @dotmashrc said, only play/pause button is displayed when notification is collapsed. That's because I use ExoPlayer's `PlayerNotificationManager` to create notifications. It turns out that `PlayerNotificationManager` isn't doing well. There's also an issue in #333. The solution is to write my own code to manage notification, but I'm not inclined to do this now.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/39427017/199029214-cf553f9a-2ff3-4e39-8283-3ab6b5cf5dca.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/39427017/199029333-7865909f-f5e3-4bbb-857a-0ad8b4b7a8c2.png">

**Comment by owencz1998** [comment] 2022-10-31 14:41
No worries there's no expanding when your on the lock screen it wouldn't be so bad if it expanded but that's all good dude thanks 👍

**Comment by Ereshkigal01** [comment] 2023-01-04 05:07
I can confirm that this issue is still present on the latest version. 
When on lock screen and single swipe in notification panel the seek , next and previous buttons aren't coming up. It's only coming up when you swipe down twice to get into quick settings. 

I am using Lineage OS19 which is pretty much vanilla Android 12. I have also tried with other apps like ViMuisc but they are working as expected. 

Screenshot attached for lockscreen, single swipe and double swipe notification panel.
![Screenshot_20230104-103006_Trebuchet2](https://user-images.githubusercontent.com/95167142/210488175-1d4753ed-6a9d-475f-8285-0120dbd3427c.png)
![Screenshot_20230104-103100_Trebuchet](https://user-images.githubusercontent.com/95167142/210488178-acaf9060-ba22-4ee1-8668-f58043374960.png)
![Screenshot_20230104-102945_Trebuchet](https://user-images.githubusercontent.com/95167142/210488182-5f7a5679-e12c-4a84-831b-3a5b58633543.png)

**Comment by A37stKpDodi4BEr65TXb** [comment] 2023-01-10 13:35
I'm on LineageOS 19 as well and no media control in notification is the only issue that really stops me from using this app full time.

Not sure how useful this might be to the dev, I'm using [Auxio](https://github.com/OxygenCobalt/Auxio) which is also built of off Exoplayer, and it works well.

**Comment by Rayforest** [comment] 2023-02-07 13:17
> I'm on LineageOS 19 as well and no media control in notification/on lockscreen is the only issue that really stops me from using this app full time.

Ah, same for me. I was so happy finding this app and only realised how much a forward and backward button really mattered after not having them in the music player. It is okay in the homescreen cuz a single more tap expands the music player. The main issue is the lockscreen, because we can only play/pause it in the home screen and to play next or previous we have to unlock the phone

Well ig there is nothing doing about it cuz the issue has already been closed. Is there some way to change this exoplayer. Maybe use the code of viplayer or something. I prefer this app's ui and recommendations over ViMusic.

@z-huang Do you know why this only happen to some users and not others, any idea? Just fyi, my android version is 11 and running on realme 2 ui.
![Screenshot_2023-02-07-18-25-18-89_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/124686957/217254700-7b3d2ae9-4448-4f7d-8daf-92e4a22303f2.jpg)
![Screenshot_2023-02-07-18-25-22-82_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/124686957/217254713-ea6196b8-5af2-467b-bf69-134045a06271.jpg)
![Screenshot_2023-02-07-18-25-25-71_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/124686957/217254718-f8c9992c-c1f8-4f57-bd3d-d28fa33f55c4.jpg)

**Comment by z-huang** [comment] 2023-02-08 06:20
Sorry, I have no idea. I just don't have time on this issue. PR is welcomed.

**Comment by Rayforest** [comment] 2023-02-11 08:50
> PR is welcomed.
Ah, I wish I could help you there. But I don't know anything about coding and tbh I am even new to GitHub.

Just had a question... Isn't ViMusic open source? They don't seem to have this problem either in the Music player in the homescreen or the lockscreen. Is it possible to look at their source code and maybe solve this problem

(Attaching ss from ViMusic music player)

![Screenshot_2023-02-11-14-15-56-46_6f55a3c4de83481ebdee1685416eed82.jpg](https://user-images.githubusercontent.com/124686957/218249323-96b25712-afcb-468b-9cb6-d6a5fdc20874.jpg)

![Screenshot_2023-02-11-14-16-01-51_6f55a3c4de83481ebdee1685416eed82.jpg](https://user-images.githubusercontent.com/124686957/218249324-068b3a7e-02d5-4ca9-824b-3cb226d82795.jpg)

**Comment by Rayforest** [comment] 2023-02-11 08:51
> PR is welcomed.

Ah, I wish I could help you there. But I don't know anything about coding and tbh I am even new to GitHub.

Just had a question... Isn't ViMusic open source? They don't seem to have this problem either in the Music player in the homescreen or the lockscreen. Is it possible to look at their source code and maybe solve this problem

(Attaching ss from ViMusic music player)

![Screenshot_2023-02-11-14-15-56-46_6f55a3c4de83481ebdee1685416eed82.jpg](https://user-images.githubusercontent.com/124686957/218249384-2b5a98aa-8ab4-4483-99c1-8910ec870347.jpg)

![Screenshot_2023-02-11-14-16-01-51_6f55a3c4de83481ebdee1685416eed82.jpg](https://user-images.githubusercontent.com/124686957/218249385-acf27d85-d0e6-4a78-9008-a8e252726261.jpg)

**Comment by z-huang** [comment] 2023-06-20 14:03
Fixed by migrating to media3.

**Closed by z-huang** 2023-06-20 14:03 UTC
Labels: enhancement, low priority

**Comment by Rayforest** [comment] 2023-09-16 17:59
> Fixed by migrating to media3.

Thank you soooo much. You are awesome 🥰😍❤️‍🔥
