### ISSUE TITLE
Wrong lyrics in other languages

### ISSUE THREAD

**Issue by Denpun1** [z-huang/InnerTune#589] opened 2023-02-21 14:16 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Set the language to Japanese.
2. Open the lyrics of a song like "Hated by life itself." by "Will Stetson".

### Expected behavior

This should show the correct lyrics in any language.

### Actual behavior

This displays wrong lyrics.

### Screenshots/Screen recordings

![Screenshot_2023-02-20-01-08-25-422_com zionhuang music debug](https://user-images.githubusercontent.com/110000352/220364035-fad1a215-c68f-49ad-bd3e-cd215bbc16e2.jpg)
↑Japanese 1
![Screenshot_2023-02-20-01-08-30-411_com zionhuang music debug~01](https://user-images.githubusercontent.com/110000352/220364064-6c5f741d-21e4-4119-aad2-688f5586e39c.jpg)
↑Japanese 2　(Wrong lyrics)

![Screenshot_2023-02-20-01-08-53-009_com zionhuang music debug](https://user-images.githubusercontent.com/110000352/220364210-87759fe0-fd88-4961-96f0-6d1e947c0920.jpg)
↑English 1
![Screenshot_2023-02-20-01-10-34-222_com zionhuang music debug](https://user-images.githubusercontent.com/110000352/220364273-41e35a50-f300-470a-89e2-19231b12c0dd.jpg)
↑English 2　(Correct lyrics)

### Music version

0.44

### Android version

Android12

**Comment by z-huang** [comment] 2023-02-21 15:06
Duplicate of #585

**Closed by z-huang** 2023-02-21 15:06 UTC
Labels: bug
