### ISSUE TITLE
Can you make it possible so we can save & download our imported playlists from Spotify and YouTube? 

### ISSUE THREAD

**Issue by GoD1nZ** [z-huang/InnerTune#615] opened 2023-03-14 16:08 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Currently this app does not allow me to import playlists from Spotify or YouTube, I would like to import and either save the playlist by liking the whole playlist so I can have it in my Albums & would love to be able to download the songs at high quality to the phone storage for offline usage.

### Why do you want this feature?

I want this future because it is not in the current version of the App.

**Comment by owencz1998** [comment] 2023-03-14 17:00
Spotify importing I don't think will be added but you can already import yt music playlists

**Comment by owencz1998** [comment] 2023-03-14 19:43
Make sure your playlist is open and not private then search for it in innertune the name of your playlist or your name then it should show

**Comment by z-huang** [comment] 2023-04-29 04:00
Duplicate of #518 and #499.

**Closed by z-huang** 2023-04-29 04:00 UTC
Labels: enhancement
