### ISSUE TITLE
Local Files support

### ISSUE THREAD

**Issue by yellowshouldhaveneverbeenaprimarycolor** [z-huang/InnerTune#539] opened 2023-01-29 18:34 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

play local files inside the app

### Why do you want this feature?

I dont want to switch my music player all the time

**Comment by owencz1998** [comment] 2023-01-29 18:51
Duplicate of #3

**Closed** 2023-01-30 06:32 UTC
Labels: duplicate, enhancement
